name: CI

on: [push, pull_request]

permissions:
  contents: write

jobs:
  test-runner:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'liberica'
          java-version: '11'
      - uses: DeLaGuardo/setup-clojure@12.1
        with:
          cli: latest
      - run: clojure -X:test/kaocha
      - uses: coverallsapp/github-action@v2
        with:
          file: target/coverage/coveralls.json
